# Generated by Django 5.0.2 on 2024-02-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('roll', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField()),
                ('city', models.CharField()),
                ('pincode', models.IntegerField()),
                ('addr_type', models.CharField(choices=[('R', 'Residence'), ('P', 'Permanent'), ('C', 'Communication')], default='R', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
