# Generated by Django 5.0.2 on 2024-02-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_address_addr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='student_app.student'),
        ),
    ]
